package assignmentlab;
import java.util.Scanner;
import java.lang.String;

public class Main {
	public static void main(String args[]) {
		Scanner input = new Scanner(System.in);
		String universe;
		String city;
		String name, realname, job, desc, weapon, attack;
		int age, weaponstr, physicalstr, calorie, speed;
		boolean fly;
		System.out.println("Please enter the name of your superhero universe: ");
		universe = input.nextLine();
		System.out.println(" ");
		System.out.println("Welcome to the " + universe + " Superhero Universe!");
		System.out.println(" ");
		System.out.println("Please enter the setting of your superhero universe: ");
		city = input.nextLine();
		System.out.println(" ");
		System.out.println("It was a dark and gloomy night in " + city + "...");
		System.out.println("Suddenly, a maniacal laughter fills the alleyways, a villain has struck the city and they won't rest until " + city + " is destroyed for good!");
		System.out.println("It is now your job to assemble a group of superheroes who can defeat the evil and restore peace to the city.");
		System.out.println(" ");
		System.out.println("But first, let's assess who our opponent is!");
		System.out.println(" ");
		System.out.println("Enter the details for " + city + "'s most notorious villain!");
		System.out.println("Villain Name: ");
		name = input.nextLine();
		System.out.println("Villain's Real Name: ");
		realname = input.nextLine();
		System.out.println("Villain's job: ");
		job = input.nextLine();
		System.out.println("Villain's motives: ");
		desc = input.nextLine();
		System.out.println("Villain's weapon: ");
		weapon = input.nextLine();
		System.out.println("What is the villain's attack's name?");
		attack = input.nextLine();
		System.out.println("Villain's age: ");
		age = input.nextInt();
		System.out.println("Can the villain fly?");
		fly = input.nextBoolean();
		System.out.println("What is the villain's weapon strength?");
		weaponstr = input.nextInt();
		
		villain vill = new villain(name, realname, job, desc, age, fly, attack, weapon, weaponstr);
		System.out.println(" ");
		System.out.println(vill);
		System.out.println(" ");
		
		System.out.println("Now it is time to assemble our legion of saviours.");
		System.out.println("Your objective is to assemble a group of 8 heroes that will consist of 2 from each of the following categories: ");
		System.out.println(" ");
		System.out.println("1. Physical Hero \r\n2. Mage Hero \r\n3. Vigilante \r\n4. Speedster");
		System.out.println(" ");
		input.nextLine();
		
			System.out.println("Enter the details for Physical Hero no 1");
			System.out.println("Hero Name: ");
            name = input.nextLine();		
			System.out.println("Hero's Real Name: ");
			realname = input.nextLine();
			System.out.println("Hero's job: ");
			job = input.nextLine();
			System.out.println("Hero Description: ");
			desc = input.nextLine();
			System.out.println("What is the hero's attack's name?");
			attack = input.nextLine();
			System.out.println("Hero's age: ");
			age = input.nextInt();
			System.out.println("Can the hero fly?");
			fly = input.nextBoolean();
			System.out.println("What is the hero's physical strength value?");
			physicalstr = input.nextInt();
			PhysicalHero ph1 = new PhysicalHero (name, realname, job, desc, age, fly, attack, physicalstr);
			System.out.println(ph1);
			System.out.println(" ");
			input.nextLine();
			
			System.out.println("Enter the details for Physical Hero no 2");
			System.out.println("Hero Name: ");
			name = input.nextLine();
			System.out.println("Hero's Real Name: ");
			realname = input.nextLine();
			System.out.println("Hero's job: ");
			job = input.nextLine();
			System.out.println("Hero Description: ");
			desc = input.nextLine();
			System.out.println("What is the hero's attack's name?");
			attack = input.nextLine();
			System.out.println("Hero's age: ");
			age = input.nextInt();
			System.out.println("Can the hero fly?");
			fly = input.nextBoolean();
			System.out.println("What is the hero's physical strength value?");
			physicalstr = input.nextInt();
			int power3;
			System.out.println("Enter the physical strength boost used by the physical heroes: ");
			power3 = input.nextInt();
			PhysicalHero ph2 = new PhysicalHero (name, realname, job, desc, age, fly, attack, physicalstr);
			System.out.println(ph2);
			System.out.println(" ");
			input.nextLine();
			
			System.out.println("Enter the details for Mage Hero no 1");
			System.out.println("Hero Name: ");
            name = input.nextLine();		
			System.out.println("Hero's Real Name: ");
			realname = input.nextLine();
			System.out.println("Hero's job: ");
			job = input.nextLine();
			System.out.println("Hero Description: ");
			desc = input.nextLine();
			System.out.println("What is the hero's attack's name?");
			attack = input.nextLine();
			System.out.println("Hero's age: ");
			age = input.nextInt();
			System.out.println("Can the hero fly?");
			fly = input.nextBoolean();
			System.out.println("What is the hero's Mana value?");
			physicalstr = input.nextInt();
			MageHero mh1 = new MageHero (name, realname, job, desc, age, fly, attack, physicalstr);
			System.out.println(mh1);
			System.out.println(" ");
			input.nextLine();
			
			System.out.println("Enter the details for Mage Hero no 2");
			System.out.println("Hero Name: ");
            name = input.nextLine();		
			System.out.println("Hero's Real Name: ");
			realname = input.nextLine();
			System.out.println("Hero's job: ");
			job = input.nextLine();
			System.out.println("Hero Description: ");
			desc = input.nextLine();
			System.out.println("What is the hero's attack's name?");
			attack = input.nextLine();
			System.out.println("Hero's age: ");
			age = input.nextInt();
			System.out.println("Can the hero fly?");
			fly = input.nextBoolean();
			System.out.println("What is the hero's Mana value?");
			physicalstr = input.nextInt();
			int power2;
			System.out.println("Enter the magik power boost used by the MageHeroes: ");
			power2 = input.nextInt();
			MageHero mh2 = new MageHero (name, realname, job, desc, age, fly, attack, physicalstr);
			System.out.println(mh2);
			System.out.println(" ");
			input.nextLine();
			
			System.out.println("Enter the details for Vigilante no 1");
			System.out.println("Hero Name: ");
            name = input.nextLine();		
			System.out.println("Hero's Real Name: ");
			realname = input.nextLine();
			System.out.println("Hero's job: ");
			job = input.nextLine();
			System.out.println("Hero Description: ");
			desc = input.nextLine();
			System.out.println("What is the hero's weapon's name?");
			weapon = input.nextLine();
			System.out.println("What is the hero's attack's name?");
			attack = input.nextLine();
			System.out.println("Hero's age: ");
			age = input.nextInt();
			System.out.println("Can the hero fly?");
			fly = input.nextBoolean();
			System.out.println("What is the hero's weapon's strength?");
			physicalstr = input.nextInt();
			Vigilante vh1 = new Vigilante (name, realname, job, desc, age, fly, attack, weapon, physicalstr);
			System.out.println(vh1);
			System.out.println(" ");
			input.nextLine();
			
			System.out.println("Enter the details for Vigilante no 2");
			System.out.println("Hero Name: ");
            name = input.nextLine();		
			System.out.println("Hero's Real Name: ");
			realname = input.nextLine();
			System.out.println("Hero's job: ");
			job = input.nextLine();
			System.out.println("Hero Description: ");
			desc = input.nextLine();
			System.out.println("What is the hero's weapon's name?");
			weapon = input.nextLine();
			System.out.println("What is the hero's attack's name?");
			attack = input.nextLine();
			System.out.println("Hero's age: ");
			age = input.nextInt();
			System.out.println("Can the hero fly?");
			fly = input.nextBoolean();
			System.out.println("What is the hero's weapon's strength?");
			physicalstr = input.nextInt();
			int power;
			System.out.println("Enter the attack power used by the vigilantes: ");
			power = input.nextInt();
			Vigilante vh2 = new Vigilante (name, realname, job, desc, age, fly, attack, weapon, physicalstr);
			System.out.println(vh2);
			System.out.println(" ");
			input.nextLine();
			
			System.out.println("Enter the details for Speedster no 1");
			System.out.println("Hero Name: ");
            name = input.nextLine();		
			System.out.println("Hero's Real Name: ");
			realname = input.nextLine();
			System.out.println("Hero's job: ");
			job = input.nextLine();
			System.out.println("Hero Description: ");
			desc = input.nextLine();
			System.out.println("What is the hero's attack's name?");
			attack = input.nextLine();
			System.out.println("Hero's age: ");
			age = input.nextInt();
			System.out.println("Can the hero fly?");
			fly = input.nextBoolean();
			System.out.println("What is the hero's physical strength value?");
			physicalstr = input.nextInt();
			System.out.println("What is the hero's calorie intake?");
			calorie = input.nextInt();
			System.out.println("What is the hero's top speed?");
			speed = input.nextInt();
			Speedster sh1 = new Speedster (name, realname, job, desc, age, fly, attack, physicalstr, speed, calorie);
			System.out.println(sh1);
			System.out.println(" ");
			input.nextLine();
			
			System.out.println("Enter the details for Speedster no 2");
			System.out.println("Hero Name: ");
            name = input.nextLine();		
			System.out.println("Hero's Real Name: ");
			realname = input.nextLine();
			System.out.println("Hero's job: ");
			job = input.nextLine();
			System.out.println("Hero Description: ");
			desc = input.nextLine();
			System.out.println("What is the hero's attack's name?");
			attack = input.nextLine();
			System.out.println("Hero's age: ");
			age = input.nextInt();
			System.out.println("Can the hero fly?");
			fly = input.nextBoolean();
			System.out.println("What is the hero's physical strength value?");
			physicalstr = input.nextInt();
			System.out.println("What is the hero's calorie intake?");
			calorie = input.nextInt();
			System.out.println("What is the hero's top speed?");
			speed = input.nextInt();
			int power1;
			System.out.println("Enter the speed boost used by the speedsters: ");
			power1 = input.nextInt();
			Speedster sh2 = new Speedster (name, realname, job, desc, age, fly, attack, physicalstr, speed, calorie);
			System.out.println(sh2);
			System.out.println(" ");
			input.nextLine();
			
			System.out.println("Wonderful! Your group of heroes is ready to fight for the city. Let the battle commence!");
			
			
			vill.attack(vill.attack_name);
			mh1.spells("suffer");
			mh1.attack(mh1.attack_name, 700);
			vill.suffer();
			vh1.attack(vh1.attack_name, power);
			vh1.rest(vh1.potion_number);
			vill.suffer();
			sh1.attack(sh1.attack_name, power1);
			sh2.attack(sh2.attack_name, power1);
			vill.suffer();
			ph1.attack(ph1.attack_name);
			ph2.attack(ph2.attack_name);
			ph1.rest();
			ph2.rest();
			mh1.attack(mh1.attack_name, power2);
			ph1.attack(ph1.attack_name, power3);
			ph2.attack(ph2.attack_name, power3);
			vill.suffer();
			ph1.rest(ph1.potion_number);
			ph2.rest(ph2.potion_number);
			vill.suffer();
			if(vill.weapon_strength < 100) {
			System.out.println("The " + universe + " have successfully defeated " + vill.Hero_Name);
			System.out.println("Peace has been restored to the city.");
			}
	
	}
}
